### ISSUE TITLE
arg() method doesn’t work

### ISSUE THREAD

**Issue by Shlurp** [ichbinderwooj/complex#1]
tan theta = b/a
theta = atan( b/a) + pi • k

You don’t take the whole pi • k into account, so if theta is more than 90 (or less than 0) you’ll get the incorrect and/or negative answer.

**Comment by ichbinderwooj** [comment]
i tried something else. thanks for letting me know

**Comment by ichbinderwooj** [comment]
nope its even worse

**Comment by ichbinderwooj** [comment]
should work now
